import { Outfit } from "next/font/google"
import "./globals.css";
import Header from "./_component/Header";
import dotenv from 'dotenv';

dotenv.config();
import NextAuthSessionProvider from "./provider";
import { Toaster } from "sonner";
const geistSans = Outfit({
  subsets: ["latin"]
});
const geistMono = Outfit({
  subsets: ["latin"]
});
// const intter = Outfit({ })
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthSessionProvider>

          <div className="">
            < Header />
            < Toaster />
            {children}
          </div>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
